[package]
name = "slice-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[[bin]]
name = "slice"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
ctrlc.workspace = true
cpp_demangle.workspace = true
object.workspace = true
slice-core = { path = "../slice-core" }
slice-render = { path = "../slice-render" }
slice-ebpf = { path = "../slice-ebpf" }

[dev-dependencies]
assert_cmd.workspace = true
predicates.workspace = true
tempfile.workspace = true

[lints]
workspace = true
